### ISSUE TITLE
2018-07-03

### ISSUE THREAD

**Issue by tataqiuqiu** [liuguanyu/quiz-every-meeting#17]
出个css的题吧。
没有找到合适的图片，下边的图是个大概。
实际要求是最后一行后边要缩进5个字符。其它不变。
可以不兼容ie。

![Image of Yaktocat](http://www.daqianduan.com/wp-content/uploads/2015/10/dome2.png)

```html
<p>这里的字有很多很多，但是只能显示三行。而且最后一行还要末尾缩进5个字符，还要有省略号。你会怎么实现呢？</p>
```

**Comment by tataqiuqiu** [comment]
图片从网上找的，题目要求是最后一行要缩进5个字符。用css实现这样的效果。不考虑ie浏览器。

**Comment by liuguanyu** [comment]
只能用css吧

**Comment by liuguanyu** [comment]
先来个耍赖皮的
```html
<style>
p {
    transform:rotate(180deg); 
    text-indent: 5em;
    width: 180px;
    padding: 5px;
}
</style>
<p>这里的字有很多很多，但是只能显示三行。而且最后一行还要末尾缩进5个字符，还要有省略号。你会怎么实现呢？</p>
```

**Comment by tataqiuqiu** [comment]
这是一个很神奇的写法~
```css
// 只显示4行，超过的用省略号表示
.ellipsis-4-line{
    position: relative;
    max-height: rem(160);/*用像素表示，不要用em，以免造成不同浏览器下计算出现小数点取舍不同导致1像素的差距【行高*截取行数】*/
    overflow: hidden;
    word-wrap: break-word;
    word-break: break-all;/*强制打散字符*/
    line-height: rem(40);
    color: #fff;/*同背景色*/
    &::before,
    &::after{
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        color: #888;/*实际文本颜色*/
        content: attr(title);
    }
    &::before{
        display: block;
        z-index: 1;/*显示在最上面，展示前面的(截取行数-1)行字符*/
        max-height: rem(120);/*根据行高和截取行数调整，值为[(截取行数-1)*行高]*/
        overflow: hidden;
        background-color: #fff;/*同背景色*/
    }
    &::after{
        display: -webkit-box;
        -webkit-box-orient:vertical;
        -webkit-box-sizing:border-box;
        box-sizing:border-box;
        text-overflow: ellipsis;
        -webkit-line-clamp: 4;/*截取行数*/
        text-indent: -10em;/*行首缩进字符数，值为[-(截取行数-1)*尾部留空字符数]，取负值把每行多padding-right的部分给缩进回去*/
        padding-right: 3em;/*尾部留空字符数*/
        /*margin-left: -3em;*/
    }
}
```
