### ISSUE TITLE
番外题 - 多行文字对齐

### ISSUE THREAD

**Issue by chunpu** [liuguanyu/quiz-every-meeting#31]
请实现这种效果

在分开的盒子里面, 可以实现第一行, 第二行都对齐, 但里面的字体大小是不一样的

![image](https://user-images.githubusercontent.com/4565306/45730286-68902100-bc03-11e8-9516-5d3ef82c5118.png)

下面为 html 模板

```html
<body>
  <style>
.wrapper {
  display: flex;
}
.item {
  border: 1px solid red;
  margin: 10px;
  padding: 5px;
}
/* 请在此处解答 */

  </style>
  <div class="wrapper">
    <div class="item">
      <div class="line-1">
        line1
        <span>00</span>
      </div>
      <div class="line-2">line2</div>
    </div>
    <div class="item">
      <div class="line-1">
        line1
        <span style="font-size: 30px;">00</span>
      </div>
      <div class="line-2">line2</div>
    </div>
    <div class="item">
      <div class="line-1">
        line1
        <span>00</span>
      </div>
      <div class="line-2">line2<span style="font-size: 30px;">00</span></div>
    </div>
  </div>
  <script>
console.log([...document.querySelectorAll('.item')].map(item => {
  return `top: ${item.offsetTop} height: ${item.offsetHeight}`
}))
  </script>
</div>
</body>
```

**Comment by mileOfSunshine** [comment]
<details>
  <summary>点击查看详细内容</summary>

```html
<body>
  <style>
  .wrapper {
    display: flex;
  }
  .item {
    border: 1px solid red;
    margin: 10px;
    padding: 5px;
  }
  /* 请在此处解答 */
  .cross-align-baseline {
    align-items: baseline
  }
  .flex-row {
    display: flex;
    flex-direction: row
  }
  .flex-col {
    display: flex;
    flex-direction: column
  }
  .line-1::after,
  .line-2::after {
    content: '.';
    width: 0;
    font-size: 30px;
    color: transparent;
  }
  </style>
  <div class="wrapper flex-row cross-align-baseline">
    <div class="item flex-col">
      <div class="line-1 flex-row cross-align-baseline">
        line1
        <span>00</span>
      </div>
      <div class="line-2">line2</div>
    </div>
    <div class="item flex-col">
      <div class="line-1 flex-row cross-align-baseline">
        line1
        <span style="font-size: 30px;">00</span>
      </div>
      <div class="line-2">line2</div>
    </div>
    <div class="item flex-col">
      <div class="line-1 flex-row cross-align-baseline">
        line1
        <span>00</span>
      </div>
      <div class="line-2">line2<span style="font-size: 30px;">00</span></div>
    </div>
  </div>
  <script>
console.log([...document.querySelectorAll('.item')].map(item => {
  return `top: ${item.offsetTop} height: ${item.offsetHeight}`
}))
  </script>
</div>
</body>
```

</details>

**Comment by liuguanyu** [comment]
```css
  .wrapper {
  	align-items: baseline;
  }	

  .item {
  	display: flex;
  	flex-flow: column nowrap;
  }

  .line-1, .line-2, .line-1 *, .line-2 *{
	line-height: 30px;
	display: inline-block;
  }
```

**Comment by tataqiuqiu** [comment]
```css
.wrapper {
  display: flex;
}
.item {
  border: 1px solid red;
  margin: 10px;
  padding: 5px;
  display: flex;
  align-content: flex-end;
  flex-wrap: wrap;
}
.item div:nth-child(1){
  width: 100%;
  line-height: 30px;
}
```
