### ISSUE TITLE
2018-9-28 纯css绘制鹰嘴型

### ISSUE THREAD

**Issue by tataqiuqiu** [liuguanyu/quiz-every-meeting#34]
尝试画个鹰嘴型
（不要求100%一致，是个鹰嘴型就可以啦）
![Image of Yaktocat](http://p0.qhimg.com/t011c3dac9c3e194861.jpg)

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta content="yes" name="apple-touch-fullscreen" />
    <meta content="telephone=no,email=no" name="format-detection" />
    <style>
        body{
            text-align: center;
        }
        .icon{
            display: inline-block;
            width: 60px;
            height: 100px;
            margin: 100px 30px;
            
           /* 答案写这里 */
        }
        .icon--blue{
            /* 答案写这里 */
        }
    </style>
</head>
<body>
<span class="icon"></span>
<span class="icon icon--blue"></span>
</body>
```

**Comment by chunpu** [comment]
`toLocaleString`

**Comment by mileOfSunshine** [comment]
<details>
  <summary>点击有惊喜</summary>

![image](https://user-images.githubusercontent.com/17926741/46240799-5ec6a480-c3df-11e8-92ff-460b77c8ed48.png)


```html
<style>
body{
    text-align: center;
}
.icon{
    position: relative;
    display: inline-block;
    width: 60px;
    height: 100px;
    margin: 100px 30px;
    
   /* 答案写这里 */
   height: 60px;
   background: #000;
   border-top-left-radius: 100%;
}
.icon::after {
    position: absolute;
    top: 30px;
    left: 0;
    content: '';
    width: 60px;
    height: 30px;
    border-top-left-radius: 100%;
    background-color: #fff;
}
.icon--blue{
    /* 答案写这里 */
    height: 70px;
    background-color: blue;
}
.icon--blue::after {
    height: 40px;
}
</style>
```
</details>

**Comment by liuguanyu** [comment]
<details>
  <summary>用scale试一下</summary>

```html
    <style>
        body{
            text-align: center;
        }
        .icon{
            display: inline-block;
            width: 60px;
            height: 100px;
            margin: 100px 30px;
            
           /* 答案写这里 */ 
           position: relative;
           border-top-left-radius: 100%;
           background: #000;
        }
        .icon--blue{
            /* 答案写这里 */
            background: blue;
        }

        .icon::after {
            position: absolute;
            bottom: 0;
            left: 0;
            width:60px;
            height: 100px;
            content: '';
            background-color: #fff;
            border-top-left-radius: 100%;
            transform: scaleY(.5) translateY(50px);
        }
    </style>
```
</details>

**Comment by liuguanyu** [comment]
<details>
  <summary>来个精简的</summary>

```html
    <style>
        body{
            text-align: center;
        }
        .icon{
            display: inline-block;
            width: 60px;
            height: 100px;
            margin: 100px 30px;
            
           /* 答案写这里 */ 
            border-bottom: 60px solid transparent;
            border-left: 80px solid #000;
            border-top-left-radius: 100%;;

            transform: rotateX(180deg) rotateZ(-90deg);
        }
        .icon--blue{
            /* 答案写这里 */
            border-left-color: blue;
        }
    </style>
```
</details>

**Comment by tataqiuqiu** [comment]
<details>
  <summary>科科</summary>

```html
<style>
        body{
            text-align: center;
        }
        .icon{
            display: inline-block;
            width: 60px;
            height: 100px;
            margin: 100px 30px;

           /* 答案写这里 */
            border-top: 30px solid #000;
            border-top-left-radius: 55px 60px;
        }
        .icon--blue{
           /* 答案写这里 */
            border-top-left-radius: 60px 70px;
            border-color: blue;
        }
    </style>
```

</details>

**Comment by chunpu** [comment]
<details>
  <summary>刮奖</summary>

```css
.icon{
    display: inline-block;
    width: 100px;
    height: 100px;
    margin: 100px 30px;

    /* 答案写这里 */
    position: relative;
    border-top-left-radius: 100%;
    background: #000;
    overflow: hidden;
}
.icon--blue{
    /* 答案写这里 */
    background: blue;
}

.icon::after {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 200px;
    height: 200px;
    content: '';
    background-color: white;
    border-radius: 1000px;
    top: 50px;
    left: -13px;
}
```

</details>

**Comment by anjia** [comment]
<details>
  <summary>第一反应 <a href="https://codepen.io/anjia/pen/QZvjNz">在线预览</a></summary>

```css
.icon{
  display: inline-block;
  width: 60px;
  height: 100px;
  margin: 100px 30px;

  /* 答案写这里 */
  --color: black;
  position: relative;
  background-color: var(--color);
  border-radius: 100% 0 0 0;
}
.icon--blue{
  /* 答案写这里 */
  --color: blue;
}
.icon::before {
  content: '';
  position: absolute; left: 0; bottom: 0; width: 100%; height: 50%;
  background-color: white;
  border-radius: 100% 0 0 0;
}
```
</details>

**Comment by anjia** [comment]
<details>
  <summary>第一反应 <a href="https://codepen.io/anjia/pen/QZvjNz">在线预览</a></summary>

```css
.icon{
  display: inline-block;
  width: 60px;
  height: 100px;
  margin: 100px 30px;

  /* 答案写这里 */
  --color: black;
  position: relative;
  background-color: var(--color);
  border-radius: 100% 0 0 0;
}
.icon--blue{
  /* 答案写这里 */
  --color: blue;
}
.icon::before {
  content: '';
  position: absolute; left: 0; bottom: 0; width: 100%; height: 50%;
  background-color: white;
  border-radius: 100% 0 0 0;
}
```
</details>

**Comment by anjia** [comment]
<details>
  <summary>2. <a href="https://codepen.io/anjia/pen/PymZBw">在线预览</a></summary>

```css
.icon{
  display: inline-block;
  width: 60px;
  height: 100px;
  margin: 100px 30px;

  /* 答案写这里 */
  --color: black;
  --len1: 100%;
  background-image: radial-gradient(ellipse 100% 40% at bottom right, white 0, white var(--len1), var(--color) var(--len1), var(--color));
  border-radius: 100% 0 0 0;
}
.icon--blue{
  /* 答案写这里 */
  --color: blue;
}
```
</details>

**Comment by anjia** [comment]
<details>
  <summary>2.2 纯点的 <a href="https://codepen.io/anjia/pen/rqmLBX">在线预览</a></summary>

```css
.icon{
  display: inline-block;
  width: 60px;
  height: 100px;
  margin: 100px 30px;

  /* 答案写这里 */
  --color: black;
  --len1: 100%;
  background-color: var(--color);
  background-image:
    radial-gradient(ellipse 100% 40% at bottom right, white 0, white var(--len1), transparent var(--len1), transparent),
    radial-gradient(ellipse 100% 100% at bottom right, transparent 0, transparent var(--len1), white var(--len1), white);
}
.icon--blue{
  /* 答案写这里 */
  --color: blue;
}
```
</details>
